server:
  port: 8082

spring:
  application:
    name: order-service  # Tên service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Kết nối đến Eureka Server
  instance:
    prefer-ip-address: true
