# spring:
#   application:
#     name: user-service

#   config:
#     import: "optional:configserver:http://localhost:8888"

#   cache:
#     type: redis  
#     redis:
#       time-to-live: 600000
  
# jwt:
#   secret: eF4$Kf!3v9XzQrL8mT#92hJxw@0N1GzD
#   accessToken:
#     expiration: 3600000
#   refreshToken:
#     expiration: 604800000

# logging:
#   level:
#     org.springframework.security: DEBUG



server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 phút (ms)


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}
  accessToken:
    expiration: 3600000       # 1 giờ (ms)
  refreshToken:
    expiration: 604800000     # 7 ngày (ms)

logging:
  level:
    org.springframework.security: DEBUG
internal:
  api:
    key: ${API_KEY_INTERNAL}