
# spring:
#   application:
#     name: api-gateway

#   config:
#     import: "configserver:http://localhost:8888"  
#     # import: "optional:configserver:http://host.docker.internal:8888"
#   profiles:
#     active: dev
  


server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: dev


  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api/v1/roles/**, /api/v1/auth/**
     
        - id: course-service
          uri : lb://course-service
          predicates:
            - Path=/api/v1/categories/**, /api/v1/courses/**, /api/v1/lessons/**, /api/v1/lessons/**

        - id: review-service
          uri : lb://review-service
          predicates:
            - Path=/api/v1/reviews/**

        - id: payment-service
          uri : lb://payment-service
          predicates:
            - Path=/api/v1/paymentMethods/**, /api/v1/payments/**

        - id: notification-service
          uri : lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**

        - id: enrollment-service
          uri : lb://enrollment-service
          predicates:
            - Path=/api/v1/enrollments/**, /api/v1/lesson-progress/**

        - id: quiz-service
          uri : lb://quiz-service
          predicates:
            - Path=/api/v1/quizs/**, /api/v1/quiz-attempts/**

        - id: discount-service
          uri : lb://discount-service
          predicates:
            - Path=/api/v1/discounts/**
        
        - id: aggregation-service
          uri : lb://aggregation-service
          predicates:
            - Path=/api/v1/aggregated/courses/**, /api/v1/aggregated/enrollments/**, /api/v1/aggregated/lesson_progress/**, /api/v1/aggregated/teacher/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
        
 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

jwt:
  secret: ${JWT_SECRET}

gateway:
  public:
    paths: 
      POST /api/v1/auth/**,
      GET /api/v1/users/by-ids,
      GET /api/v1/categories,
      GET /api/v1/courses,
      GET /api/v1/paymentMethods,
      GET /api/v1/users/*/exists,
      GET /api/v1/aggregated/courses/**
