
spring:
  application:
    name: api-gateway

  config:
    import: "configserver:http://localhost:8888"  
    # import: "optional:configserver:http://host.docker.internal:8888"
  profiles:
    active: dev
  
